name: Run Tests

on:
  pull_request:
    branches: [master, main, feature/hasanati-islamic-app]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs
        continue-on-error: true

      - name: Analyze code
        run: flutter analyze
        continue-on-error: true

      - name: Run Tests
        run: flutter test
        continue-on-error: true